---
- name: ACLs gathered
  hosts: routers
  gather_facts: no
  tasks:
    - name: Delete module attributes of given Interface
      cisco.ios.ios_acls:
        state: deleted
      register: output
    
    - name: debug message
      debug:
        var: output