---
- name: network L2 interfaces
  hosts: R2
  gather_facts: no
  tasks:
    - name: Render the commands for provided configuration
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/2
            ipv4:
              - address: 1.1.1.1/24
              - address: 2.2.2.2/24
                secondary: true
              - address: 3.3.3.3/24
                secondary: true
        state: replaced
      register: output
      
    - name: debug message
      debug:
        msg: "{{ output }}"